management.endpoints:
 web.exposure.include: "health"
 health.show-details: "always"

com.msag.securityInfo:
 gateway:
  userName: "aspirant"
  pwd: ${NEWS_PWD}
  generalNews:
   url: "https://news-api-78bda.web.app/general-news"
  videoNews:
   url: "https://news-api-78bda.web.app/video-news"



